apiVersion: v1
kind: Service
metadata:
  name: hotelapi-service
  namespace: homeinns-pms
spec:
  selector:
    app: hotelapi
  # type  暴露端口类型： ClusterIP (默认值)  、  NodePort   、   externalIPs
  type: NodePort
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5005
      #30000-32767 
      nodePort: 32555
