apiVersion: v1
kind: Pod
metadata: 
 name: hotelapi-hostpath-pod 
 namespace: homeinns-pms
spec: 
  #restartPolicy：  Always 容器失效则重启 ， OnFailure  退出码不为0时则重启   ，  Never  不管结果如何都不重启 
 restartPolicy: Never
 containers: 
    - name: hotelapi 
      # imagePullPolicy： Always 总是拉取镜像 /  Never  只使用本地镜像  / IfNotPresent 优先本地，没有则拉取
      imagePullPolicy: Always
      image: registry.cn-hangzhou.aliyuncs.com/yxdeng/dyx_image:hotel-api-pod
      ports:
       - containerPort: 5005
      args: 
       - /bin/sh 
       - -c for i in {1..100};do echo $i >> /data/hotel.txt
       - sleep 36000 
      # 磁盘卷
      volumeMounts: 
       #磁盘卷名称
       - name: data 
         # 文件路径
         mountPath: /data 
  # 映射到容器内部 磁盘卷
 volumes: 
 - name: data 
   hostPath: 
    #文件名称
    path: /tmp
    #挂在卷类型
    type: Directory