apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pms-role-binding
  namespace: homeinns-pms
subjects:
- kind: User
  name: user-dyx
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pms-role
  apiGroup: rbac.authorization.k8s.io
