
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: homeinns-pms
spec:
  tracing:
    # 设置采样率，可以用来控制追踪功能是否开启
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9412/api/v2/spans"