apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyx-sa
  namespace: homeinns-pms
#secrets:
#  # 秘钥文字--3.Secret.ali.registry.yaml
#  - name: dyx-ali-harbor-secret
#拉取镜像 使用的秘钥  
# deployment ----> sa ---> secret  3.Secret.ali.registry.yaml
imagePullSecrets:
  - name: dyx-ali-harbor-secret
   