apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
 name: hotelapi-pvc
 namespace: homeinns-pms
spec: 
   #存储模式
   accessModes: 
   # accessModes 节点取值范围：
   #   1.ReadWriteOnce（RWO）：读写权限，但是只能被单个节点挂载 
   #   2.ReadOnlyMany （ROX）：只读权限，可以被多个节点挂载 
   #   3.ReadWriteMany（RWX）：读写权限，可以被多个节点挂载 
   - ReadWriteMany 
   resources: 
    requests: 
     storage: 1Gi
   # 选测器, 如果设置，默认也会匹配大小相同，且未分配的PV
   selector:
      matchLabels:
       app: "hotelapipv"