# 3. Secret Management        秘密管理
# 我这里列了一些常用的配置，更多Secret Management 信息请参考官方文档: https://docs.dapr.io/zh-hans/reference/components-reference/supported-secret-stores/
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local.secret.component
  namespace: homeinns-pms
spec:
  # secret 中间件类型支持 10余种中间件： secretstores.local.file , Kubernetes 等等++...ing
  #  设置Kubernetes密钥仓库不需要特殊的配置，你能够从 http://localhost:3500/v1.0/secrets/kubernetes/[my-secret] 这个 URL中获取配置信息。
  # 此处使用local.file 状态存储中间件
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    # 存储路径 （存储密钥的文件路径）
    value: C:\Users\Dyx\source\repos\Micro.Hotel.API\local.secret.component.json
  - name: nestedSeparator
    # 在将JSON层次结构 嵌套分隔符 。 即： (connectionStrings:sql) 来访问密钥 。 默认值 ":"
    value: ":"